### ISSUE TITLE
hamburger-animation() not working: No items for 'nth'

### ISSUE THREAD

**Issue by smichaelsen** [mrmlnc/hamburger-icon#1]
`hamburger-generator()` work great but when I use `hamburger-animation()` I get the following error on the console:

```
Error: List index is 1 but list has no items for `nth'
    on line 68 of project/sass/lib/_hamburger-icon.scss, in `hamburger-animation'
    from line 37 of project/sass/style.scss
    from line 11 of project/sass/main.scss
  Use --trace for backtrace.
Warning: Exited with error code 65 Use --force to continue.
```

This is how I call it:

```
.menu-icon {
  span {
    @include hamburger-generator($_width, $_thickness, $_gap, $color: $_color, $timing-function: linear);
  }
  float: left;
  margin-top: rem-calc(12);
}
nav.open .menu-icon span {
  @include hamburger-animation();
}
```

When I patch the `hamburger-animation()` mixin so that I can set `$width` and `$gutter` explicitly per argument instead of getting them from `$hamburger-settings` everything is fine, but it was better if your solution worked.

**Comment by mrmlnc** [comment]
I am having the exact same problem with official compiler (Sass 3.x.x) and have not yet found a solution.

There is no problem when using LibSass.

**Comment by mrmlnc** [comment]
This problem is specific to the official compiler. When using libSass it does not arise. I changed the declaration of global variables. Aaaaaaand It works!
