### ISSUE TITLE
double pseudo elements

### ISSUE THREAD

**Issue by derhedwig** [mrmlnc/hamburger-icon#3]
Hi!
You have a subtle bug in hamburger-icon.scss resulting in double pseudo elements. Chrome somehow copes with that, but Firefox just ignores the top and the bottom bar...

The problem starts in line 50: 
<code>&:before, &:after {</code> are nested inside <code>&, &:before, &:after {</code>

**Comment by mrmlnc** [comment]
Yeap!

Fixed in [v1.0.3](https://github.com/mrmlnc/hamburger-icon/releases/tag/1.0.3).

Thanks for pointing the error!
